export enum KeySymbol {
  Enter = "↵",
  Backspace = "⌫",
  Tab = "⇥",
  Shift = "⇧",
  Control = "⌃",
  Alt = "⎇",
  Meta = "⌘",
  Escape = "⎋",
  ArrowUp = "↑",
  ArrowDown = "↓",
  ArrowLeft = "←",
  ArrowRight = "→",
  Insert = "⎀",
  Delete = "⌦",
  Home = "⇱",
  End = "⇲",
  PageUp = "⇞",
  PageDown = "⇟",
  CapsLock = "⇪",
  NumLock = "⇭",
  ScrollLock = "⇳",
  Pause = "⎉",
  PrintScreen = "⎙",
  ContextMenu = "≣",
}